let car = 'BMW';
console.log("Is car == 'BMW'? I predict True.");
console.log(car == 'BMW');
let flower = 'Tulips'
console.log("Is flower == 'Tulips'? I predict True.");
console.log(flower == 'Tulips');
let softdrink = 'ColaNext';
console.log("Is softdrink == 'ColaNext'? I predict True.");
console.log(softdrink == 'ColaNext');
let phonebrand = 'Samsung';
console.log("Is phonebrand == 'Samsung'? I predict True.");
console.log(phonebrand == 'Samsung');
let Clothebrand = 'Nakoosh';
console.log("Is Clothebrand == 'Nakoosh'? I predict True.");
console.log(Clothebrand == 'Nakoosh');
let laptop = 'gucci';
console.log("Is laptop !== 'gucci'? I predict False.");
console.log(laptop !== 'gucci');
let moltyfoam = 'dell';
console.log("Is moltyfoam !== 'dell'? I predict False.");
console.log(moltyfoam !== 'dell');
let powerbank = 'Alvsin';
console.log("Is powerbank !== 'Alvsin'? I predict False.");
console.log(powerbank !== 'Alvsin');
let Footballer = 'Babar Azam';
console.log("Is Footballer !== 'Babar Azam'? I predict False.");
console.log(Footballer !== 'Babar Azam');
let F1RACER = 'Ronaldo';
console.log("Is F1RACER !== 'Ronaldo'? I predict False.");
console.log(F1RACER !== 'Ronaldo');